
// Bridge generated by makeFormForReaders.js
// include..... repository: solidStateNMRCSA-reader
// include..... jsLibrary: [object Object],[object Object],[object Object],[object Object]
// work on object:NMRspinSystemModel_CSA (object == className)
// Auto-generated supplement file for className:NMRspinSystemModel_CSA to objectTarget: NMRspectrumObject
NMRspectrumObject_DataEnrichment(targetObjType, dataObj = {}) {
	const myName = "NMRspectrumObject_DataEnrichment"; // don't automatize in case 'use strict'
	if (targetObjType == "info") {
		return {
			targetObjType: "NMRspectrumObject",
			uniqueHTMLcode: myName,
			elevatorMethod: myName,
			creatorParam: {"editor":"djeanner","version":"1","source":"solidStateNMRCSA","id":"none"},
			arrayOfItems: [
				{
					type: "file",
					htmlID: "jsonSpectrum",
					comment: "NMR file (.json) - testing needing input file to complement one object towards another",
					show: true
				},
{
					type: "baseType",
					htmlID: "origin",
					baseType: "string",
					comment: "origin",
					defaultValue: "Insert here the source of the data",
					show: true
				},
{
					type: "baseType",
					htmlID: "frequency",
					baseType: "double",
					comment: "Larmor frequency",
					defaultValue: 500,
					randomFrom: 100,
					randomTo: 500,
					show: true
				}
			],
		};
	}


	// Handle fields dynamically

	var newFields = {};

	
	const jsonSpectrum = this.#getValOrDefault(dataObj, "jsonSpectrum");
	if (jsonSpectrum !== undefined) newFields["jsonSpectrum"] = jsonSpectrum;
	

	const origin = this.#getValOrDefault(dataObj, "origin");
	if (origin !== undefined) newFields["origin"] = origin;
	

	const frequency = this.#getValOrDefault(dataObj, "frequency");
	if (frequency !== undefined) newFields["frequency"] = frequency;
	
	
	// optional escape 
	if ( 
		(false)
	) {
		const errorMessage = "Failed because of missing input1";
		document.getElementById(
			`mergeOutput${dataObj.uniqueHTMLcode}`
		).textContent = errorMessage;
		return;
	}

	
	const creatorParam = dataObj.creatorParam; 

	const theNMRspinSystemModel_CSA = new NMRspinSystemModel_CSA([], this.obj);
	console.log("7777")


	
	const param = {
		//dataObj : dataObj,
		//objDataField: dataObj.item.objDataField,
		creatorParam : creatorParam,
		object: "nmrSpectrumObject", // NMRspectrumObject
		//objectObj: dataObj.objectObj,
        newFields
		};
	const retData = theNMRspinSystemModel_CSA._saveExportedData(param);
	const targetData = {
		"$schema" :`https://chemedata.github.io/schema/v1/schema/nmrSpectrumObject.json`,
		...retData
	};

	const targetContent = {content : targetData};

	const encodedContent1 = JSON.stringify(targetContent);
	const linkUrl = `nmrSpectrumObject.html#data=${encodedContent1}`;

	//This dumps the json in the cell / may be too long
	//document.getElementById(`mergeOutput${dataObj.uniqueHTMLcode}`).textContent = JSON.stringify(targetData, null, 2);

	console.log("linkUrl.length",linkUrl.length)
	console.log("Valid URL?", /^[ -~]+$/.test(linkUrl));
	if (linkUrl.length > 10000) {
		localStorage.clear();
		const storageKey = `data_${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
		localStorage.setItem(storageKey, encodedContent1);
		const linkUrlShort = `${encodeURIComponent("nmrSpectrumObject")}.html#storageKey=${storageKey}`;
		console.log("localStorage linkUrlShort.length",linkUrlShort.length)
		console.log("Valid localStorage URL?", /^[ -~]+$/.test(linkUrlShort));
		window.open(linkUrlShort, "_blank");
	} else {
		window.open(linkUrl, "_blank");
	}
}
