
// generated by makeFormForReaders.js
// include..... repository: MnovaJson-reader
// include..... jsLibrary: mnovaJsonReader.js
// work on object:nmrSpectrumObject (object == className)
// Auto-generated supplement file for className:nmrSpectrumObject
nmrSpectrumObject_DataEnrichment(targetObjType, dataObj = {}) {
	const myName = "nmrSpectrumObject_DataEnrichment"; // don't automatize in case 'use strict'
	if (targetObjType == "info") {
		return {
			targetObjType: "nmrSpectrumObject",
			uniqueHTMLcode: myName,
			elevatorMethod: myName,
			arrayOfItems: [
				{
					type: "file",
					htmlID: "jsonSpectrum",
					comment: "NMR file (.json)",
					show: true
				}
			],
		};
	}

	var sourceObj = {};

	// Handle fields dynamically
	
	const jsonSpectrum = this.#getValOrDefault(dataObj, "jsonSpectrum");
	if (jsonSpectrum !== undefined) sourceObj["jsonSpectrum"] = jsonSpectrum;
	
	// optional escape sourceObj
	if ( 
		(sourceObj && Object.keys(sourceObj).length === 0)
					// tests input1 as field.dataPropertyName above test
					//!document.getElementById(`input1${dataObj.uniqueHTMLcode}`).dataset
					//	.content
	) {
		const errorMessage = "Failed because of missing input1";
		document.getElementById(
			`mergeOutput${dataObj.uniqueHTMLcode}`
		).textContent = errorMessage;
		return;
	}

	sourceObj["$schema"] = `https://chemedata.github.io/schema/v1/schema/${targetObjType}.json`;
	// TAKE CARE OF ORIGIN
	sourceObj["origin"] = {};///// TO DO


	//const creatorParam = {creatorParam:dataObj.creatorParam}; 
	const creatorParam = dataObj.creatorParam; 
	// here create object, call converter...

	const thenmrSpectrumObject = new NMRspectrumObject(creatorParam, sourceObj);
	console.log("3333p")
	console.log("5555")

	const targetData = {content :thenmrSpectrumObject.data};

	if ( 
		(targetData && Object.keys(targetData).length === 0)
	) {
		const errorMessage = "targetData is empty";
		document.getElementById(
			`mergeOutput${dataObj.uniqueHTMLcode}`
		).textContent = errorMessage;
		return;
	}

	const encodedContent1 = JSON.stringify(targetData);
	const linkUrl = `${targetData}.html#data=${encodedContent1}`;

	//This dumps the json in the cell / may be too long
	//document.getElementById(`mergeOutput${dataObj.uniqueHTMLcode}`).textContent = JSON.stringify(targetData, null, 2);

	console.log("linkUrl.length",linkUrl.length)
	console.log("Valid URL?", /^[ -~]+$/.test(linkUrl));
	if (linkUrl.length > 1000) {
		localStorage.clear();
	    const storageKey = `data_${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
	    localStorage.setItem(storageKey, JSON.stringify(targetData));
	    const linkUrlShort = `html/${encodeURIComponent(targetObjType)}.html#storageKey=${storageKey}`;
		console.log("localStorage linkUrlShort.length",linkUrlShort.length)
		console.log("Valid localStorage URL?", /^[ -~]+$/.test(linkUrlShort));
		window.open(linkUrlShort, "_blank");
	} else {
		window.open(linkUrl, "_blank");
	}
}
