
// Viewer generated by makeFormForReaders.js
// include..... repository: CHEMeDATA/NMRspectrum-viewer
// include..... jsLibrary: undefined
	setSpectra_AdditionalViewer() {
		const objClassName = "setSpectra";
		const myName = `${objClassName}_AdditionalViewer`; // function name don't use js feature in case 'use strict'

		function callGenerationGraphic(myName, viewerDataPassed) {
			const frame = document.createElement("div");
			frame.id = myName;
			frame.className = "frame red-frame";
			const container = document.getElementById("dynamicContent");
			container.appendChild(frame);
			// const svg = d3.select("#" + myName).append("svg").attr("width", 200).attr("height", 100);
			const svg = d3.select("#" + myName)
				.append("svg")
				.attr("viewBox", "0 0 900 500") // may be controled by frame size
				.style("width", "100%") // scales with container
				.style("height", "auto")
				.style("display", "block");

			var theNmrSpectrum = new NmrSpectrum(viewerDataPassed, svg);
		}

		const viewerDataPassed = NmrSpectrum.getProperDataForVisualization(this, objClassName);
		callGenerationGraphic(myName, viewerDataPassed);
	}
