// ES module
import fs from "fs";
import path from "path";
import {
	schemaRoot,
	schemaDir,
	instanceDir,
	dataDir,
	derivationsFile,
	objectsFile,
} from "../scripts/config.js";

export function checkSchemaTypes(obj, path = "") {
	const allowedTypes = [
		"object",
		"array",
		"string",
		"number",
		"integer",
		"boolean",
		"null",
	];

	for (const key in obj) {
		const value = obj[key];
		const currentPath = path ? `${path}.${key}` : key;

		if (key === "type") {
			if (typeof value === "string") {
				if (!allowedTypes.includes(value)) {
					throw new Error(
						`Invalid type "${value}" found at path "${currentPath}". ` +
							`Allowed types: ${allowedTypes.join(", ")}`
					);
				}
			} else if (Array.isArray(value)) {
				for (const v of value) {
					if (!allowedTypes.includes(v)) {
						throw new Error(
							`Invalid type "${v}" found in array at path "${currentPath}". ` +
								`Allowed types: ${allowedTypes.join(", ")}`
						);
					}
				}
			} else {
				throw new Error(
					`Invalid "type" value (not string/array) at path "${currentPath}".`
				);
			}
		}

		// Recurse into nested objects/arrays
		if (typeof value === "object" && value !== null) {
			checkSchemaTypes(value, currentPath);
		}
	}
}

export function setFieldTrue(array, fieldName) {
	return array.map((prop) =>
		prop.name === fieldName ? { ...prop, required: true } : { ...prop }
	);
}

// Allows to create a object type with only the mandatory fields 
export function createNewSetTrueFromRef(
	base,
	derived,
	fields,
	listStringSetTrue
) {
	var propDer = fields;
	listStringSetTrue.forEach((prop) => {
		propDer = setFieldTrue(propDer, prop);
	});
	const derivationsFileNameIn = path.join(".", derivationsFile);
	createNewTypeSchema(derived, propDer);
	addDerivation(derivationsFileNameIn, base, derived, listStringSetTrue, false);
}

// Throw error helper
function generateError(message) {
	throw new Error("❌ " + message);
}

// Compact numeric arrays in JSON string, insert line breaks every lineLength chars
function compactNumericArrays(jsonString, lineLength = 100) {
	function processArray(content) {
		let depth = 0;
		let start = 0;
		let result = "";

		for (let i = 0; i < content.length; i++) {
			const char = content[i];
			if (char === "[") {
				if (depth === 0) start = i;
				depth++;
			} else if (char === "]") {
				depth--;
				if (depth === 0) {
					const inner = content.slice(start + 1, i);
					const compactedInner = processArray(inner);
					result += `[${compactedInner}]`;
					continue;
				}
			}

			if (depth === 0) result += char;
		}

		const items = result.split(",").map((s) => s.trim());
		const allNumbers = items.every(
			(item) => !isNaN(Number(item)) && item !== ""
		);
		if (allNumbers) {
			const joined = items.join(", ");
			let final = "";
			for (let i = 0; i < joined.length; i += lineLength) {
				final += joined.slice(i, i + lineLength) + "\n";
			}
			return final.trim();
		}

		return result;
	}

	let stack = [];
	let output = "";
	let startIdx = null;

	for (let i = 0; i < jsonString.length; i++) {
		const char = jsonString[i];
		if (char === "[") {
			if (stack.length === 0) startIdx = i;
			stack.push("[");
		} else if (char === "]") {
			stack.pop();
			if (stack.length === 0 && startIdx !== null) {
				const content = jsonString.slice(startIdx + 1, i);
				const compacted = processArray(content);
				output += `[${compacted}]`;
				startIdx = null;
				continue;
			}
		}

		if (stack.length === 0 && char !== "]") {
			output += char;
		}
	}

	return output;
}

function ensureDerivationsFile(derivationsFileNameIn) {
	if (!fs.existsSync(derivationsFileNameIn)) {
		const initialData = {
			_comment: "This file is automatically generated. Do not edit manually.",
			derivations: [],
		};
		fs.writeFileSync(
			derivationsFileNameIn,
			JSON.stringify(initialData, null, 4),
			"utf8"
		);
	}
}

function addDerivation(
	derivationsFileNameIn,
	base,
	derived,
	fieldsToAdd,
	isFiedlToAdd = true
) {
	ensureDerivationsFile(derivationsFileNameIn);
	const content = JSON.parse(fs.readFileSync(derivationsFileNameIn, "utf8"));
	if (isFiedlToAdd) {
		content.derivations.push({ base, derived, fieldsToAdd });
	} else {
		content.derivations.push({ base, derived, fieldsSetTrue: fieldsToAdd });
	}
	fs.writeFileSync(
		derivationsFileNameIn,
		JSON.stringify(content, null, 4),
		"utf8"
	);
}

function ensureObjectsFile(ObjectsFileNameIn) {
	if (!fs.existsSync(ObjectsFileNameIn)) {
		const initialData = {
			_comment: "This file is automatically generated. Do not edit manually.",
			_comment2: "Will have float and double as type for numbers",
			objects: [],
		};
		fs.writeFileSync(
			ObjectsFileNameIn,
			JSON.stringify(initialData, null, 4),
			"utf8"
		);
	}
}

function addObject(ObjectsFileNameIn, base, fields) {
	ensureObjectsFile(ObjectsFileNameIn);
	const content = JSON.parse(fs.readFileSync(ObjectsFileNameIn, "utf8"));
	content.objects.push({ name: base, fields: fields });
	fs.writeFileSync(ObjectsFileNameIn, JSON.stringify(content, null, 4), "utf8");
}

// Derive a schema
export function deriveSchema(sourceClass, derivedClass, fieldsToAdd) {
	const sourcePath = path.join(schemaDir, `${sourceClass}.json`);
	const derivedPath = path.join(schemaDir, `${derivedClass}.json`);
	const derivationsFileNameIn = path.join(".", derivationsFile);

	addDerivation(derivationsFileNameIn, sourceClass, derivedClass, fieldsToAdd);

	console.log(`🛠️ Deriving ${sourceClass} into ${derivedClass}...`);
	console.log(
		`   Adding fields:`,
		fieldsToAdd
			.map((f) => `${f.name} (${f.type})${f.mandatory ? " [mandatory]" : ""}`)
			.join(", ")
	);

	const sourceSchema = JSON.parse(fs.readFileSync(sourcePath, "utf8"));

	const derivedSchema = {
		$schema: sourceSchema["$schema"],
		type: sourceSchema["type"],
		$id: `${schemaRoot}${derivedClass}.json`,
		allOf: [{ $ref: sourceSchema["$id"] }],
		properties: {},
	};

	const requiredFields = [];
	fieldsToAdd.forEach((field) => {
		derivedSchema["properties"][field.name] = { type: field.type };
		if (field.type === "float")
			derivedSchema["properties"][field.name] = { type: "number" };
		if (field.type === "double")
			derivedSchema["properties"][field.name] = { type: "number" };
		if (field.mandatory) {
			requiredFields.push(field.name);
		}
	});

	// Add required fields if any
	if (requiredFields.length > 0) {
		derivedSchema["required"] = requiredFields;
	}
	checkSchemaTypes(derivedSchema);
	fs.writeFileSync(derivedPath, JSON.stringify(derivedSchema, null, 4));
	console.log(`✅ ${derivedClass} schema created at:`, derivedPath);
}

/**
 * Create a JSON Schema based on provided properties
 * @param {string} newSchemaName - The name of the new schema (without .json)
 * @param {Array} propertiesList - An array defining properties with attributes
 */
export function createNewTypeSchema(newSchemaName, propertiesList) {
	if (!newSchemaName || !propertiesList) {
		generateError("Missing required parameters");
	}
	const schemaPath = path.join(schemaDir, `${newSchemaName}.json`);
	console.log(`🛠️ Creating schema: ${newSchemaName}...`);
	const ObjectsFileNameIn = path.join(".", objectsFile);
	addObject(ObjectsFileNameIn, newSchemaName, propertiesList);
	const properties = {};
	const requiredFields = [];

	propertiesList.forEach((prop) => {
		let propSchema;
		if (prop.array) {
			if (prop.type === "object" && prop.ref) {
				propSchema = {
					type: "array",
					items: { $ref: `${schemaRoot}${prop.ref}.json` },
				};
			} else {
				// Regular array of basic types
				propSchema = { type: "array", items: { type: prop.type } };
				if (prop.type === "float")
					propSchema = { type: "array", items: { type: "number" } };
				if (prop.type === "double")
					propSchema = { type: "array", items: { type: "number" } };
			}
		} else {
			// Single objects or primitives
			if (prop.type === "object" && prop.ref) {
				propSchema = { $ref: `${schemaRoot}${prop.ref}.json` };
			} else {
				propSchema = { type: prop.type };
				if (prop.type === "float") propSchema = { type: "number" };
				if (prop.type === "double") propSchema = { type: "number" };
			}
		}

		properties[prop.name] = propSchema;

		if (prop.required) {
			requiredFields.push(prop.name);
		}
	});

	const newSchema = {
		$schema: "http://json-schema.org/draft-07/schema#",
		type: "object",
		$id: `${schemaRoot}${newSchemaName}.json`,
		properties: properties,
		required: requiredFields.length > 0 ? requiredFields : undefined,
	};
	checkSchemaTypes(newSchema);
	fs.writeFileSync(schemaPath, JSON.stringify(newSchema, null, 4));
	console.log(`✅ ${newSchemaName} schema created at:`, schemaPath);
}

// Create instance
export function createInstance(objName, schemaName, dataInput) {
	let large = false;
	if (typeof dataInput === "string") {
		dataInput = dataInput.replace(
			/_INSERT_FILE-([\s\S]*?)__/g,
			(match, fileName) => {
				console.log(`*******fileName: ${fileName}`);

				let filePath = path.join(instanceDir, fileName + ".json");
				if (!fs.existsSync(filePath)) {
					// fallback to dataDir if file not in instanceDir
					filePath = path.join(dataDir, fileName + ".json");
				}
				try {
					const fileContent = fs.readFileSync(filePath, "utf-8");
					return fileContent;
				} catch (err) {
					console.error(`⚠️ Could not read file: ${filePath}`, err);
					return `"ERROR: missing file ${fileName}"`;
				}
			}
		);
		try {
			large = dataInput.length > 300000;
			dataInput = JSON.parse(dataInput);
		} catch (err) {
			console.error("Invalid JSON string:", err.message);
			throw new Error("❌ ");
		}
	}

	/*if (large) {
		dataInput.splice(5);
		console.warning("chapped arrays ");
	}*/

	if (!schemaName || !objName || !dataInput)
		generateError("Missing required parameters");

	const instancePath = path.join(instanceDir, `${objName}.json`);
	const data = {
		$schema: `${schemaRoot}${schemaName}.json`,
		wildComment:
			"Created by schema/scripts/createSchemaSomeInstances.js using function createInstance",
		...dataInput,
	};
	console.log("is large", large);
	if (large) {
		const constString = JSON.stringify(data);
		fs.writeFileSync(instancePath, constString);
	} else {
		const constString = JSON.stringify(data, null, 4);
		const constString2 = compactNumericArrays(constString);
		fs.writeFileSync(instancePath, constString2);
	}

	console.log(`✅ ${objName} instance created at:`, instancePath);
}
