import { classHandlerSupFiles } from "../scripts/config.js";
import fs from "fs";
import path from "path";
const urlLocalOrGithub = ""; // "https://chemedata.github.io/schema/" // ${urlLocalOrGithub}

export function generateSupplementFileImporter(config) {
	const {
		object,
		objectObj,
		type,
		jsLibrary,
		creatorParam,
		requiredInput,
		repository,
		jsLibraryGet,
		fileNameAsSavedHere
	} = config;
	console.log("******************* >>> Importer");
	console.log("object", object);
	console.log("type", type);
	console.log("jsLibrary", jsLibrary);
	console.log("creatorParam", creatorParam);
	console.log("repository", repository);
	console.log("jsLibraryGet", jsLibraryGet);
	// included objects
	const className = object;

	var includeFile = "";
	for (const item of jsLibraryGet) {
		if (item.include) {
			includeFile += `import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";\n`
			console.log(`prepare: import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";`);
		} 
	}
	const fileNameInclude = `supImpZZ_${className}.js`;
	fs.writeFileSync(path.join(classHandlerSupFiles, fileNameInclude), includeFile, "utf8");

	// main file
	const fileName = `supplement${className}.js`;
	//const creatorParamStringified = JSON.stringify(creatorParam);
			/*
			{
			 "dataPropertyName": "jsonSpectrum",
			 "label": "NMR file (.json)",
			 "type": "file",
			 "validationFileString1000": "https://mestrelab.com/json-schemas/mnova/2023-07/01/nmr/spec"
			}
			*/

	// Generate arrayOfItems content from requiredInput
	const arrayOfItems = requiredInput
		.map((field) => {
			
			if (field.type == "file") {
				return `{
					type: "file",
					htmlID: "${field.dataPropertyName}",
					comment: "${field.label}",
					show: true
				}`;
			} else {
				if (field.baseType === "string") {
					return `{
					type: "baseType",
					htmlID: "${field.dataPropertyName}",
					baseType: "${field.baseType}",
					comment: "${field.label}",
					defaultValue: "${field.defaultValue}",
					show: true
				}`;
				} else {
					return `{
					type: "baseType",
					htmlID: "${field.dataPropertyName}",
					baseType: "${field.baseType}",
					comment: "${field.label}",
					defaultValue: ${field.defaultValue},
					randomFrom: ${field.randomFrom},
					randomTo: ${field.randomTo},
					show: true
				}`;
				}	
			}
		})
		.join(",\n");

	// Generate field handling loop
	const fieldLoop = requiredInput
		.map((field) => {
			return `
	const ${field.dataPropertyName} = this.#getValOrDefault(dataObj, "${field.dataPropertyName}");
	if (${field.dataPropertyName} !== undefined) sourceObj["${field.dataPropertyName}"] = ${field.dataPropertyName};`;
		})
		.join("\n");

	// Template for the function
	const content = `
// Importer generated by makeFormForReaders.js
// include..... repository: ${repository}
// include..... jsLibrary: ${jsLibrary}
// work on object:${object} (object == className)
// Auto-generated supplement file for className:${className}
${className}_DataEnrichment(targetObjType, dataObj = {}) {
	const myName = "${className}_DataEnrichment"; // don't automatize in case 'use strict'
	if (targetObjType == "info") {
		return {
			targetObjType: "${className}",
			uniqueHTMLcode: myName,
			elevatorMethod: myName,
			creatorParam: ${JSON.stringify(creatorParam)},
			arrayOfItems: [
				${arrayOfItems}
			],
		};
	}

	var sourceObj = {};

	// Handle fields dynamically
	${fieldLoop}
	
	// optional escape sourceObj
	if ( 
		(sourceObj && Object.keys(sourceObj).length === 0)
					// tests input1 as field.dataPropertyName above test
					//!document.getElementById(\`input1\${dataObj.uniqueHTMLcode}\`).dataset
					//	.content
	) {
		const errorMessage = "Failed because of missing input1";
		document.getElementById(
			\`mergeOutput\${dataObj.uniqueHTMLcode}\`
		).textContent = errorMessage;
		return;
	}

	sourceObj["$schema"] = \`https://chemedata.github.io/schema/v1/schema/\${targetObjType.objName}.json\`;
	// TAKE CARE OF ORIGIN
	sourceObj["origin"] = {};///// TO DO

	// here create object, call converter...
	const creatorParam = dataObj.creatorParam; 

	const the${object} = new ${objectObj}(creatorParam, sourceObj);
	console.log("3333p")
	console.log("5555")

	const targetData = {content :the${object}.data};

	if ( 
		(targetData && Object.keys(targetData).length === 0)
	) {
		const errorMessage = "targetData is empty";
		document.getElementById(
			\`mergeOutput\${dataObj.uniqueHTMLcode}\`
		).textContent = errorMessage;
		return;
	}

	const encodedContent1 = JSON.stringify(targetData);
	const linkUrl = \`${urlLocalOrGithub}\${targetData}.html#data=\${encodedContent1}\`;

	//This dumps the json in the cell / may be too long
	//document.getElementById(\`mergeOutput\${dataObj.uniqueHTMLcode}\`).textContent = JSON.stringify(targetData, null, 2);

	console.log("linkUrl.length",linkUrl.length)
	console.log("Valid URL?", /^[\x20-\x7E]+$/.test(linkUrl));
	if (linkUrl.length > 10000) {
		localStorage.clear();
		const storageKey = \`data_\${Date.now()}_\${Math.floor(Math.random() * 1e6)}\`;
		localStorage.setItem(storageKey, JSON.stringify(targetData));
		const linkUrlShort = \`\${encodeURIComponent(targetObjType)}.html#storageKey=\${storageKey}\`;
		console.log("localStorage linkUrlShort.length",linkUrlShort.length)
		console.log("Valid localStorage URL?", /^[\x20-\x7E]+$/.test(linkUrlShort));
		window.open(linkUrlShort, "_blank");
	} else {
		window.open(linkUrl, "_blank");
	}
}
`;

	// Write the file
	fs.writeFileSync(path.join(classHandlerSupFiles, fileName), content, "utf8");
	console.log(`✅ File ${fileName} created successfully.`);
}