import { classHandlerSupFiles } from "../scripts/config.js";
import fs from "fs";
import path from "path";

export function generateSupplementFileExporter(config) {
	const {
		object,
		objectObj,
		type,
		jsLibrary,
		creatorParam,
		outputComponents,
		repository,
		jsLibraryGet,
		fileNameAsSavedHere,
		title
	} = config;
	console.log("******************* ");
	console.log("object", object);
	console.log("type", type);
	console.log("jsLibrary", jsLibrary);
	console.log("creatorParam", creatorParam);
	//console.log("fieldsToAdd", fieldsToAdd);
	console.log("repository", repository);
	console.log("jsLibraryGet", jsLibraryGet);
	console.log("title", title);
	// included objects
	const className = object;

	var includeFile = "";
	for (const item of jsLibraryGet) {
		if (item.include) {
			includeFile += `import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";\n`
			console.log(`prepare: import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";`);
		} 
	}
	const fileNameInclude = `supImpIn_${className}.js`;
	fs.writeFileSync(path.join(classHandlerSupFiles, fileNameInclude), includeFile, "utf8");

	// main file
	const fileName = `supImpMe_${className}.js`;
	const creatorParamStringified = JSON.stringify(creatorParam);
/*

		was 	
				{
					"dataPropertyName": "jsonSpectrum",
					"label": "NMR file (.json)",
					"type": "file",
					"validationFileString1000": "https://mestrelab.com/json-schemas/mnova/2023-07/01/nmr/spec"
				}
NEW
			{
					"objDataField" : [],
					"label": "title (.txt)",
					"type": "txt",
					"defaultFileName": "output.title",
					"type possible values" :"json binary txt"
				}

*/


	// Generate arrayOfItems content from outputComponents
	const arrayOfItems = outputComponents
		.map((field) => {
			/*
			{
				"objDataField" : [],
				"label": "title (.txt)",
				"type": "txt",
				"defaultFileName": "output.title",
				"type possible values" :"json binary txt"
			}
		   */
			if (true) {
				return `{
					objDataField: ${JSON.stringify(field.objDataField)},
					type: "${field.type}",
					htmlID: "${object}",
					label: "${field.label}",
					defaultFileName: "${field.defaultFileName}",
					show: true,
				}`;
			}
		})
		.join(",\n");
/*
	// Generate field handling loop
	const fieldLoop = fieldsToAdd
		.map((field) => {
			return `
	const ${field.dataPropertyName} = this.#getValOrDefault(dataObj, "${field.dataPropertyName}");
	if (${field.dataPropertyName} !== undefined) sourceObj["${field.dataPropertyName}"] = ${field.dataPropertyName};`;
		})
		.join("\n");
*/
	// Template for the function
	const content = `
// Exporter generated by makeFormForReaders.js
// include..... repository: ${repository}
// include..... jsLibrary: ${jsLibrary}
// work on object:${object} (object == className)
// Auto-generated supplement file for className:${className}
${className}_DataExport(targetObjType, dataObj = {}) {
	const myName = "${className}_DataExport"; // don't automatize in case 'use strict'
	if (targetObjType == "info") {
		return {
			objSource: "${className}",
			objectObj: "${objectObj}",
			title: "${title}",
			uniqueHTMLcode: myName,
			elevatorMethod: myName,
			creatorParam: ${JSON.stringify(creatorParam)},
			outputComponents: [
				${arrayOfItems}
			],
		};
	}


	// here create object from this
	const the${objectObj} = new ${objectObj}([], this.obj);
	const param = {
		dataObj : dataObj,
		objDataField: dataObj.item.objDataField,
		creatorParam : dataObj.creatorParam,
		targetObjType: targetObjType,
		object: dataObj.objSource,
		objectObj: dataObj.objectObj,
		};
	const returedExport = the${objectObj}._saveExportedData(param, this.obj);
	return returedExport;
}
`;

	// Write the file
	fs.writeFileSync(path.join(classHandlerSupFiles, fileName), content, "utf8");
	console.log(`✅ File ${fileName} created successfully.`);
}