import { classHandlerSupFiles } from "../scripts/config.js";
import fs from "fs";
import path from "path";
const urlLocalOrGithub = ""; // "https://chemedata.github.io/schema/" // ${urlLocalOrGithub}

export function generateSupplementFileBridge(config) {
	const {
		objectSchemaSource,
		object,
		objectSchemaTarget,
		objectTarget,
		formFields,
		type,
		title,
		jsLibraryGet,
		sourceVersion,
		targetVersion,
		creatorParam,
		repository,
		fileNameAsSavedHere
		} = config;
	/*
	const input = {
					// innerItem ///////////////////////////////////////////////////
					objectSchemaSource: innerItem.objectSchemaSource, // here only
					object: innerItem.object, // same
					objectSchemaTarget: innerItem.objectSchemaTarget, // here only
					objectTarget: innerItem.objectTarget, // here only
					formFields: innerItem.formFields, // here only
					//objectObj: innerItem.objectObj,
					type: innerItem.type,// OK
					title: innerItem.title, // OK
					formFields: innerItem.requiredInput, // diff
					jsLibraryGet: innerItem.jsLibraryGet,  // OK
					sourceVersion: innerItem.sourceVersion,  // OK
					targetVersion: innerItem.targetVersion,  // OK

					// item ///////////////////////////////////////////////////
					//jsLibrary: item.jsLibrary,
					creatorParam: item.creatorParam, // OK
					repository: item.repository, // OK
				};
				*/
	console.log("******************* >>> Bridge");
	console.log("object", object);
	console.log("type", type);
	console.log("creatorParam", creatorParam);
	//console.log("fieldsToAdd", fieldsToAdd);
	console.log("repository", repository);
	console.log("jsLibraryGet", jsLibraryGet);
	// included objects
	const className = object;

	var includeFile = "";
	for (const item of jsLibraryGet) {
		if (item.include) {
			includeFile += `import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";\n`
			console.log(`prepare: import { ${item.include} } from \"${fileNameAsSavedHere}/${path.basename(item.fileName)}\";`);
		} 
	}
	const fileNameInclude = `supImpAA_${className}.js`;
	fs.writeFileSync(path.join(classHandlerSupFiles, fileNameInclude), includeFile, "utf8");

	// main file
	const fileName = `supImpBB_${className}.js`;
	//const creatorParamStringified = JSON.stringify(creatorParam);
			/*
			{
			 "dataPropertyName": "jsonSpectrum",
			 "label": "NMR file (.json)",
			 "type": "file",
			 "validationFileString1000": "https://mestrelab.com/json-schemas/mnova/2023-07/01/nmr/spec"
			}
			*/

	// Generate arrayOfItems content from formFields
	const arrayOfItems = formFields
		.map((field) => {		
			if (field.type == "file") {
				return `{
					type: "file",
					htmlID: "${field.dataPropertyName}",
					comment: "${field.label}",
					show: true
				}`;
			} else {
				if (field.baseType === "string") {
					return `{
					type: "baseType",
					htmlID: "${field.dataPropertyName}",
					baseType: "${field.baseType}",
					comment: "${field.label}",
					defaultValue: "${field.defaultValue}",
					show: true
				}`;
				} else {
					return `{
					type: "baseType",
					htmlID: "${field.dataPropertyName}",
					baseType: "${field.baseType}",
					comment: "${field.label}",
					defaultValue: ${field.defaultValue},
					randomFrom: ${field.randomFrom},
					randomTo: ${field.randomTo},
					show: true
				}`;
				}
				
			}
		})
		.join(",\n");

	// Generate field handling loop
	console.log("formFields",formFields)
	const fieldLoop = formFields
		.map((field) => {
			return `
	const ${field.dataPropertyName} = this.#getValOrDefault(dataObj, "${field.dataPropertyName}");
	if (${field.dataPropertyName} !== undefined) newFields["${field.dataPropertyName}"] = ${field.dataPropertyName};
	`;
		})
		.join("\n");

	// Template for the function
	const content = `
// Bridge generated by makeFormForReaders.js
// include..... repository: ${repository}
// include..... jsLibrary: ${jsLibraryGet}
// work on object:${object} (object == className)
// Auto-generated supplement file for className:${className} to objectTarget: ${objectTarget}
${objectTarget}_DataEnrichment(targetObjType, dataObj = {}) {
	const myName = "${objectTarget}_DataEnrichment"; // don't automatize in case 'use strict'
	if (targetObjType == "info") {
		return {
			targetObjType: "${objectTarget}",
			uniqueHTMLcode: myName,
			elevatorMethod: myName,
			creatorParam: ${JSON.stringify(creatorParam)},
			arrayOfItems: [
				${arrayOfItems}
			],
		};
	}


	// Handle fields dynamically

	var newFields = {};

	${fieldLoop}
	
	// optional escape 
	if ( 
		(false)
	) {
		const errorMessage = "Failed because of missing input1";
		document.getElementById(
			\`mergeOutput\${dataObj.uniqueHTMLcode}\`
		).textContent = errorMessage;
		return;
	}

	
	const creatorParam = dataObj.creatorParam; 

	const the${object} = new ${object}([], this.obj);
	console.log("7777")


	
	const param = {
		//dataObj : dataObj,
		//objDataField: dataObj.item.objDataField,
		creatorParam : creatorParam,
		object: "${objectSchemaTarget}", // NMRspectrumObject
		//objectObj: dataObj.objectObj,
        newFields
		};
	const retData = the${object}._saveExportedData(param);
	const targetData = {
		"$schema" :\`https://chemedata.github.io/schema/v1/schema/${objectSchemaTarget}.json\`,
		...retData
	};

	const targetContent = {content : targetData};

	const encodedContent1 = JSON.stringify(targetContent);
	const linkUrl = \`${objectSchemaTarget}.html#data=\${encodedContent1}\`;

	//This dumps the json in the cell / may be too long
	//document.getElementById(\`mergeOutput\${dataObj.uniqueHTMLcode}\`).textContent = JSON.stringify(targetData, null, 2);

	console.log("linkUrl.length",linkUrl.length)
	console.log("Valid URL?", /^[\x20-\x7E]+$/.test(linkUrl));
	if (linkUrl.length > 10000) {
		localStorage.clear();
		const storageKey = \`data_\${Date.now()}_\${Math.floor(Math.random() * 1e6)}\`;
		localStorage.setItem(storageKey, encodedContent1);
		const linkUrlShort = \`\${encodeURIComponent("${objectSchemaTarget}")}.html#storageKey=\${storageKey}\`;
		console.log("localStorage linkUrlShort.length",linkUrlShort.length)
		console.log("Valid localStorage URL?", /^[\x20-\x7E]+$/.test(linkUrlShort));
		window.open(linkUrlShort, "_blank");
	} else {
		window.open(linkUrl, "_blank");
	}
}
`;

	// Write the file
	fs.writeFileSync(path.join(classHandlerSupFiles, fileName), content, "utf8");
	console.log(`✅ File ${fileName} created successfully.`);
}